Abaixo é realizado o import de "matplotlib" que serve para construção dos graficos a partir dos dados tratados, "pandas" para a analise e manipulação dos dados e o "numpy" para trabalhar com arrays e matrizes

In [47]:
import matplotlib as mp
import pandas as pd
import numpy as py

Aqui é feita a leitura dos dados do csv "tv_shows"

In [25]:
tvShows = pd.read_csv("raw/tv_shows.csv")
tvShows

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type
0,0,1,Breaking Bad,2008,18+,9.4/10,100/100,1,0,0,0,1
1,1,2,Stranger Things,2016,16+,8.7/10,96/100,1,0,0,0,1
2,2,3,Attack on Titan,2013,18+,9.0/10,95/100,1,1,0,0,1
3,3,4,Better Call Saul,2015,18+,8.8/10,94/100,1,0,0,0,1
4,4,5,Dark,2017,16+,8.8/10,93/100,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5363,5363,5713,Paradise Islands,2017,NaN,NaN,10/100,0,0,0,1,1
5364,5364,5714,Mexico Untamed,2018,NaN,NaN,10/100,0,0,0,1,1
5365,5365,5715,Wild Centeral America,2020,NaN,NaN,10/100,0,0,0,1,1
5366,5366,5716,Wild Russia,2018,NaN,NaN,10/100,0,0,0,1,1
5367,5367,5717,Fearless Adventures with Jack Randall,2018,NaN,NaN,10/100,0,0,0,1,1

Abaixo ocorre uma limpeza dos dados de "tvShows" atraves do ".dropna" que retira quaisquer linhas e colunas que tenham valores ausentes (NaN/None)

In [26]:
tvShowsClean = tvShows.dropna()

Aqui está sendo feita a filtragem dos dados das notas dos shows de tv no IMDb e no Rotten Tomatoes e uma alteração nos dados para que as notas apareçam de 0 a 100 em ambas as colunas.

In [27]:
tvShowsClean['imdb_100'] = pd.to_numeric(
    tvShowsClean['IMDb'].astype(str).str.replace('/10', ''),
    errors='coerce'
) * 10
tvShowsClean['rottenTomatoes_100'] = pd.to_numeric(
    tvShowsClean['Rotten Tomatoes'].astype(str).str.replace('/100', ''),
    errors='coerce'
)

Aqui padronizamos os valores das notas do IMDb e do Rotten Tomatoes para float.

In [28]:
tvShowsClean['imdb_100'] = tvShowsClean['imdb_100'].astype(float)
tvShowsClean['rottenTomatoes_100'] = tvShowsClean['rottenTomatoes_100'].astype(float)

Por termos acima as colunas de IMDb e Rotten Tomatoes já criadas com os valores filtrados e alterados de maneira que as notas fiquem padronizadas fazemos abaixo o drop (descarte) das colunas com os dados não filtrados para não ter duplicatas e com a "unnamed: 0" descartamos qualquer coluna sem nome no CSV

In [29]:
df_tvShows = tvShowsClean.drop(columns=['IMDb', 'Rotten Tomatoes', 'Type', 'Unnamed: 0'])

Na linha abaixo fazemos uma filtragem onde para cada show de tv haverá uma indicação de sim e não caso aquele show esteja disponível ou não para um serviço de streaming especifico

In [37]:
## df_tvShows.loc[:, colunas] = df_tvShows[colunas].replace({1: 'SIM', 0: 'NÃO'})

colunas = [c for c in df_tvShows.columns if c in ['Netflix', 'Hulu', 'Prime Video', 'Disney+']]
for c in colunas:
    df_tvShows[c] = df_tvShows[c].map({1: 'SIM', 0: 'NÃO'}).fillna(df_tvShows[c]).astype(str)

Aqui filtramos todos os shows que foram lançados depois dos anos 2000

In [38]:
df_tvShows_2000 = df_tvShows[tvShowsClean['Year'] >= 2000]

Abaixo pegamos os shows: e filtramos aqueles que tem nota maior que 70 no rotten tomatoes

In [39]:
df_tvShows_rotten_70_plus = df_tvShows_2000[df_tvShows_2000['rottenTomatoes_100'] >= 70]

Abaixo pegamos os shows: e filtramos aqueles que tem nota maior que 70 no Rotten tomatoes e no IMDb

In [40]:
df_tvShows_rotten_imdb_70_plus = df_tvShows_rotten_70_plus[df_tvShows_rotten_70_plus['imdb_100'] >= 70]

Aqui pegamos todos os shows lançados depois dos anos 2000 e filtramos apenas aqueles que são recomendados para "all"(todos), 7+(anos) e 13+(anos) e colocamos na variável "publico_infantil"



---

In [41]:
publico_infantil = df_tvShows_rotten_imdb_70_plus[tvShowsClean['Age'].isin(['all', '7+', '13+'])]

C:\Users\ninis\AppData\Local\Temp\ipykernel_4500\3443750776.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  publico_infantil = df_tvShows_rotten_imdb_70_plus[tvShowsClean['Age'].isin(['all', '7+', '13+'])]

Aqui pegamos todos os shows lançados depois dos anos 2000 e filtramos apenas aqueles que são recomendados para 16+(anos) e 18+(anos) e colocamos na variável "publico_adulto"

In [42]:
publico_adulto = df_tvShows_rotten_imdb_70_plus[tvShowsClean['Age'].isin(['16+', '18+'])]

C:\Users\ninis\AppData\Local\Temp\ipykernel_4500\3134457969.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  publico_adulto = df_tvShows_rotten_imdb_70_plus[tvShowsClean['Age'].isin(['16+', '18+'])]

Aqui exibimos os dados da variável publico infantil

In [43]:
publico_infantil

,ID,Title,Year,Age,Netflix,Hulu,Prime Video,Disney+,imdb_100,rottenTomatoes_100
5,6,Avatar: The Last Airbender,2005,7+,SIM,NÃO,SIM,NÃO,93.0,93.0
11,12,Community,2009,7+,SIM,SIM,SIM,NÃO,85.0,90.0
68,69,The Legend of Korra,2012,7+,SIM,NÃO,NÃO,NÃO,84.0,83.0
72,73,One-Punch Man,2015,7+,SIM,SIM,NÃO,NÃO,88.0,83.0
80,81,Our Planet,2019,all,SIM,NÃO,NÃO,NÃO,93.0,82.0
...,...,...,...,...,...,...,...,...,...,...
5071,5395,High School Musical: The Musical: The Series,2019,7+,NÃO,NÃO,NÃO,SIM,73.0,73.0
5074,5398,Big Shot,2021,7+,NÃO,NÃO,NÃO,SIM,75.0,71.0
5075,5399,Disney Gallery / Star Wars: The Mandalorian,2020,7+,NÃO,NÃO,NÃO,SIM,84.0,71.0
5076,5400,Phineas and Ferb,2007,all,NÃO,NÃO,NÃO,SIM,80.0,71.0
5077,5401,Bluey,2018,all,NÃO,NÃO,NÃO,SIM,96.0,71.0

Aqui exibimos os dados da variável publico adulto

In [44]:
publico_adulto

,ID,Title,Year,Age,Netflix,Hulu,Prime Video,Disney+,imdb_100,rottenTomatoes_100
0,1,Breaking Bad,2008,18+,SIM,NÃO,NÃO,NÃO,94.0,100.0
1,2,Stranger Things,2016,16+,SIM,NÃO,NÃO,NÃO,87.0,96.0
2,3,Attack on Titan,2013,18+,SIM,SIM,NÃO,NÃO,90.0,95.0
3,4,Better Call Saul,2015,18+,SIM,NÃO,NÃO,NÃO,88.0,94.0
4,5,Dark,2017,16+,SIM,NÃO,NÃO,NÃO,88.0,93.0
...,...,...,...,...,...,...,...,...,...,...
3529,3705,Hunters,2020,18+,NÃO,NÃO,SIM,NÃO,72.0,70.0
5057,5376,Loki,2021,16+,NÃO,NÃO,NÃO,SIM,85.0,95.0
5058,5377,The Mandalorian,2019,16+,NÃO,NÃO,NÃO,SIM,88.0,94.0
5059,5379,WandaVision,2021,16+,NÃO,NÃO,NÃO,SIM,80.0,89.0
5060,5381,The Falcon and the Winter Soldier,2021,16+,NÃO,NÃO,NÃO,SIM,74.0,86.0

In [45]:
print(df_tvShows)

        ID                                Title  Year  Age Netflix Hulu  \
0        1                         Breaking Bad  2008  18+     SIM  NÃO
1        2                      Stranger Things  2016  16+     SIM  NÃO
2        3                      Attack on Titan  2013  18+     SIM  SIM
3        4                     Better Call Saul  2015  18+     SIM  NÃO
4        5                                 Dark  2017  16+     SIM  NÃO
...    ...                                  ...   ...  ...     ...  ...
5336  5684                Disney Family Sundays  2019  all     NÃO  NÃO
5339  5687                           Wild Chile  2018   7+     NÃO  NÃO
5340  5688  Howie Mandel's Animals Doing Things  2018  all     NÃO  NÃO
5341  5690                          The Big Fib  2020  all     NÃO  NÃO
5342  5691         Vampirina: Ghoul Girls Rock!  2018  all     NÃO  NÃO

     Prime Video Disney+  imdb_100  rottenTomatoes_100
0            NÃO     NÃO      94.0               100.0
1            NÃO     NÃO      87.0                96.0
2            NÃO     NÃO      90.0                95.0
3            NÃO     NÃO      88.0                94.0
4            NÃO     NÃO      88.0                93.0
...          ...     ...       ...                 ...
5336         NÃO     SIM      56.0                31.0
5339         NÃO     SIM      75.0                30.0
5340         NÃO     SIM      32.0                30.0
5341         NÃO     SIM      54.0                29.0
5342         NÃO     SIM      77.0                28.0

[3207 rows x 10 columns]

Envio do CSV tratado para a pasta Trusted

In [46]:
caminho_saida = "trusted/tv_shows_trusted.csv"
df_tvShows.to_csv(caminho_saida, index=False, encoding="utf-8")

print(f"Arquivo salvo em: {caminho_saida}")

Arquivo salvo em: trusted/tv_shows_trusted.csv